spring.application.name=ShopHub
server.port=7888
spring.datasource.username=scott
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.password=tiger
spring.datasource.url=jdbc:oracle:thin:@localhost:1522:orcl

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.security.user.name=deepak
spring.security.user.password=deepak@555

logging.level.org.springframework.security=DEBUG
jwt.key=hducuivqeivcvqjcbbwdvewiucvsohbvus
